name: Test browser-actions/setup-chrome action

on: 
  workflow_dispatch:

jobs:
  setup-chrome:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: setup-chrome basic test
        uses: browser-actions/setup-chrome@v1
        with: 
          chrome-version: beta
          
      - name: get chrome version
        run: |
          echo "chrome bin is $(which chrome)"
          chrome --version
      
      - name: let's do it manually
        run: |
          curl -X GET https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb -o google-chrome-beta_current_amd64.deb
          /usr/bin/ar x google-chrome-beta_current_amd64.deb
          mkdir chrome-dir
          /usr/bin/tar -xf data.tar.xz --directory chrome-dir --strip-components 4 ./opt/google
          ls -al chrome-dir
